### ISSUE TITLE
是否会解析Private Repo

### ISSUE THREAD

**Issue by mazzzystar** [guanpengchn/github-annual-report#2]
如题，看到授权提醒了，担心此项目存在漏洞可能会导致Private Repo泄露？可否释疑。

**Comment by guanpengchn** [comment]
请求授权的时候使用了GitHub APP的OAuth机制，文档[Request a user's GitHub identity](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#1-request-a-users-github-identity)中有一个`scope`字段，其中[Availabel scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)定义了权限级别，其中`scope=repo`会获取到所有权限，`scope=public_repo`只会获取到公有仓库权限，[源代码](https://github.com/guanpengchn/github-annual-report/blob/master/src/App.js#L526)只请求了public repo，不会存在private repo泄露的风险

**Comment by mazzzystar** [comment]
@guanpengchn  感谢解释。

**Comment by guanpengchn** [comment]
@mazzzystar 不客气~~

**Comment by equationl** [comment]
> 请求授权的时候使用了GitHub APP的OAuth机制，文档[Request a user's GitHub identity](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#1-request-a-users-github-identity)中有一个`scope`字段
> 
> [Availabel scopes](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)定义了权限级别，其中`scope=repo`会获取到所有权限，`scope=public_repo`只会获取到公有仓库权限，[源代码](https://github.com/guanpengchn/github-annual-report/blob/master/src/App.js#L526)只请求了public repo，不会存在private repo泄露的风险

大佬，可是在最新的代码中，你获取repo是这样写的：
![image](https://user-images.githubusercontent.com/6501123/71569482-69a04580-2b0a-11ea-984d-8db34daffce5.png)
获取范围你填的是 "all" 
也就是 Private Repo 和 Public Repo 都获取了。

不知道是不是我理解错了呀？
虽然好像并不会显示或者储存private repo的什么东西。
