### ISSUE TITLE
2019年也接近尾声了，大佬是否改为2019年报告

### ISSUE THREAD

**Issue by lsc183754539** [guanpengchn/github-annual-report#3]
2019年也接近尾声了，大佬是否改为2019年报告

**Comment by guanpengchn** [comment]
@lsc183754539 我都没想起来哈哈

**Comment by guanpengchn** [comment]
@lsc183754539 你是看到什么了么哈哈，过两天发布一个版本会比较好用

**Comment by lsc183754539** [comment]
> @lsc183754539 你是看到什么了么哈哈，过两天发布一个版本会比较好用

好的，大佬辛苦了！
