### ISSUE TITLE
在“正在生成报告”界面卡了15+分钟

### ISSUE THREAD

**Issue by EanCuznaivy** [guanpengchn/github-annual-report#9]
是不是我领不到今年的统计数据了/:break

**Comment by guanpengchn** [comment]
@EanCuznaivy 重新进入也是这样么

**Comment by guanpengchn** [comment]
就是里面有句提示，如果长期卡住就尝试刷新或者换下浏览器

**Comment by EanCuznaivy** [comment]
@guanpengchn 是啊，重试了几次都卡在了这个界面上，在获取Commit的时候还失败了几次

**Comment by EanCuznaivy** [comment]
> 就是里面有句提示，如果长期卡住就尝试刷新或者换下浏览器

chrome和safari都试过了~

**Comment by guanpengchn** [comment]
@EanCuznaivy 看来你这提交太多了，没算出来？加我下微信吧，aaron875499765，我先去查下有没有你的数据

**Comment by EanCuznaivy** [comment]
已经解决~
